[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
savings_mxe = "qbYMA7y6zaeqxFo82VBTbmGU7kEpXgMNWm6wo7DHxdR"
savings_goal = "7yqGsfLu8hYo4ugmTC43KR8iTY7JxtLFeCoSDoRkMY47"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
